### PR TITLE
tests: cleanup journal before opening the report modal

### PR DESCRIPTION
**Pull request by KKoukiou**
Seems like the chromium used for the tests crashes when the Report dialog gets opened with the full journal input.

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]

**Comment by KKoukiou** [comment]
Missed one test - see testReportIssue. Failed [in the first run.](https://cockpit-logs.us-east-1.linodeobjects.com/pull-178-20240215-153406-3fe247dd-fedora-rawhide-boot/log.html#29-1)

**Comment by martinpitt** [comment]
This now [failed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-178-20240215-155814-89370c98-fedora-rawhide-boot/log.html#29) because the [actual journal](https://cockpit-logs.us-east-1.linodeobjects.com/pull-178-20240215-155814-89370c98-fedora-rawhide-boot/TestBasic-testReportIssue-fedora-rawhide-boot-127.0.0.2-2701-FAIL.png) only has 5 lines. Are you expecting more output there?

**Comment by martinpitt** [comment]
If this goes green, I'm fully happy with it :+1: Thanks!

**Comment by KKoukiou** [comment]
Testing farm is successfull as well - status is for some reason not propagated. https://dashboard.packit.dev/results/testing-farm/363000

**Pull request merged**
