### PR TITLE
Make boot not required

### PR DESCRIPTION
**Pull request by rvykydal**
Depends on Anaconda backend API update: https://github.com/rhinstaller/anaconda/pull/5372

### CODE REVIEW

**Comment by rvykydal** [comment]
The second commit [Use the "encryption-allowed" constraint in UI checks](https://github.com/rhinstaller/anaconda-webui/pull/95/commits/e7cb7dec4c5073100dc45f01304e1e22148ca43a) 
is independent of this update and leverages already present constraints in the device selection element:
Screenshot from 2023-12-08 09-47-02
instead of failing on the final check on 'Next':
Screenshot from 2023-12-08 09-46-35

**Comment by rvykydal** [comment]
@KKoukiou - trying to run the CI with the anaconda dependency ():
```
[rvykydal@prnot4 ~/work/git/rvykydal/anaconda-webui.1 (make-boot-not-required)]$ bots/tests-trigger 95 fedora-rawhide-boot/anaconda-pr-5372@rhinstaller/anaconda-webui
95 is not a pull request.
```

**Comment by rvykydal** [comment]
> @KKoukiou - trying to run the CI with the anaconda dependency ([rhinstaller/anaconda#5372](https://github.com/rhinstaller/anaconda/pull/5372)):
> 
> ```
> [rvykydal@prnot4 ~/work/git/rvykydal/anaconda-webui.1 (make-boot-not-required)]$ bots/tests-trigger 95 fedora-rawhide-boot/anaconda-pr-5372@rhinstaller/anaconda-webui
> 95 is not a pull request.
> ```

This was caused by `origin` pointing to my fork, using `--repo rhinstaller/anaconda-webui` fixes the issue.

**Comment by rvykydal** [comment]
Seems like the backend changes are not getting into the tests (the missing API). Locally the PRs work for me using updates.img from anaconda (script/makeupdates) merged into updates.img from webui (make create-updates.img).
https://cockpit-logs.us-east-1.linodeobjects.com/pull-95-20231211-154510-698300cc-fedora-rawhide-boot-anaconda-pr-5372-rhinstaller-anaconda-webui/log.html

**Comment by KKoukiou** [comment]
https://github.com/rhinstaller/anaconda-webui/pull/100 will fix the test failures: https://github.com/rhinstaller/anaconda-webui/pull/100

**Review by KKoukiou — APPROVED** [review]

**Comment by KKoukiou** [comment]
Pasting current failing test run for ELN and re-triggering for comparison. https://cockpit-logs.us-east-1.linodeobjects.com/pull-95-20240108-190535-af47dfc6-fedora-eln-boot/log.html

**Pull request merged**
