### PR TITLE
storage: show the partitioning request review for the 'Use configured storage'

### PR DESCRIPTION
**Pull request by KKoukiou**
When the user exits the cockpit-storage, they need to see somewhere a review of their actions. Show that as a hint item, in the scenario description.

Screen Shot 2024-02-18 at 22 31 49

### CODE REVIEW

**Comment by garrett** [comment]
A revised mockup with this idea, showing how more than one disk would look:

Welcome, disk, method_ configured storage replacement (7)

Indentation is consistent with the information, unlike the screenshot.

Not related to this PR, but you can see some differences: The screenshot shows some string changes/additions, and how items under the bullets are using darker text. (Most of this is related to the free space option.) It does, however, draw attention away from the selected option and makes things more overwhelming.

**Comment by marusak** [comment]
Nice, this is what I had in mind! I checked the code and looks good. Test or at least pixel test wold be nice though ;)

**Review by marusak — APPROVED** [review]
Danke!

**Review by garrett — APPROVED** [review]
This needs some changes, but they're cosmetic and can be addressed in a followup.

**Pull request merged**
