### PR TITLE
Spawn new Firefox for external page links utilizing MimeType=x-scheme-handler/extlink

### PR DESCRIPTION
**Pull request by KKoukiou**
[AwesomeScreenshot-10_9_2024,6_00_35PM.webm](https://github.com/user-attachments/assets/e544f3fc-f63c-4ad5-9ccc-f12a65399dce)

### CODE REVIEW

**Comment by stransky** [comment]
How do you have configured the launcher? And how do you open the external link? Please try to run on terminal

xdg-open your_link

are there more firefox instances run?

**Comment by stransky** [comment]
Please attach your config files for the x-scheme-handler/extlink here, thanks.

**Comment by KKoukiou** [comment]
@stransky After some debugging I figured out the the reason for the 'double windows' was a 'target="_blank"' attribute in the link definition.

**Comment by stransky** [comment]
> @stransky After some debugging I figured out the the reason for the 'double windows' was a 'target="_blank"' attribute in the link definition.

Awesome!

**Comment by KKoukiou** [comment]
@stransky is almost works nice, just one last detail that I was not able to figure  out yet. Maybe you have it easier. 
href links that are clicked are working as expected, with opening the extlink links into the new browser window.

However, we have for the 'Report a bug' dialog another way to open the link to bugzilla, with the filled report.

This uses window.open("https://bugzilla.redhat.com.. following the details of the bug filled it.

I replaced the https with extlink like in the hrefs, and this indeed opens a new browser window, but additionaly it opens a blank tab in the current anaconda-webui browser.

I can easily reproduce if I write `window.open("extlink://github.com")` in the anaconda-webui browser console.

Any suggestions what is the difference between href link handling and window.open. 

Thanks in advance.

**Comment by KKoukiou** [comment]
@stransky can you take a look at https://github.com/rhinstaller/anaconda-webui/pull/428#issuecomment-2349654696 please for some hint?

**Comment by stransky** [comment]
Sorry for the delay, will look at it.

**Comment by stransky** [comment]
Can you post me an example of the broken link which creates extra tab? I tested it and I can't reproduce. I testes random concur link like:
`
<a href="extlink://us2.concursolutions.com/nui/signin?targetURL=%2Fnui%2Fexpense%2Freport%2F3F3ED96FABE14717B07B">External launcher 2</a>
`
an it works as expected.

**Comment by stransky** [comment]
Please share full href link which is broken for you.
Thanks.

**Comment by KKoukiou** [comment]
@stransky links with href work as expected. (See comment https://github.com/rhinstaller/anaconda-webui/pull/428#issuecomment-2349654696)

The problem is that we have one Link in the UI - where we need cant specify href (<a href=...) but instead we asynchronously run `window.open` with the `onClick` event.

This causes the problem. You can easily reproduce if you write window.open("extlink://github.com") in the anaconda-webui browser console.

**Comment by stransky** [comment]
Can you attach the webpage you use which contains the window.open() code?

**Comment by KKoukiou** [comment]
> Can you attach the webpage you use which contains the window.open() code?

The window.open is ran from the browser console where Web UI runs. How do you want me to attach that web page?

**Comment by stransky** [comment]
If you ask users to submit the bug report, which HTML/JS construction is used by Web UI HTML code to perform it? Does the Web UI HTML page contains something like:

`
<input type='button' value='Submit' onclick='window.open("extlink://github.com")'>
`
or so?

Or do you ask users to open browser console and type window.open() there?

**Comment by KKoukiou** [comment]
@stransky oh sure - it's a `<a onclick='window.open("extlink://github.com")'>`

**Comment by stransky** [comment]
<a onclick='window.open("extlink://github.com")'> doesn't produce any visible HTML element which can be clicked on. Are you sure it's correct? Please provide me complete HTML code of the page. Thanks.

**Comment by stransky** [comment]
Okay, I expect you use something like
`
<a onclick='window.open("extlink://github.com")'>Submit</a>
`

**Comment by stransky** [comment]
You may use window.location.replace() instead of open():
`
<a onclick='window.location.replace("extlink://github.com")'>Submit</a>
`

**Comment by KKoukiou** [comment]
> `<a onclick='window.open("extlink://github.com")'>` doesn't produce any visible HTML element which can be clicked on. Are you sure it's correct? Please provide me complete HTML code of the page. Thanks.

The HTML content as copied as from browser is:
``` html
<a aria-disabled="false" class="pf-v5-c-button pf-m-primary pf-m-progress" data-ouia-component-type="PF5/Button" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Button-primary-2"><span class="pf-v5-c-button__icon pf-m-start"><svg class="pf-v5-svg" viewBox="0 0 512 512" fill="currentColor" aria-hidden="true" role="img" width="1em" height="1em"><path d="M432,320H400a16,16,0,0,0-16,16V448H64V128H208a16,16,0,0,0,16-16V80a16,16,0,0,0-16-16H48A48,48,0,0,0,0,112V464a48,48,0,0,0,48,48H400a48,48,0,0,0,48-48V336A16,16,0,0,0,432,320ZM488,0h-128c-21.37,0-32.05,25.91-17,41l35.73,35.73L135,320.37a24,24,0,0,0,0,34L157.67,377a24,24,0,0,0,34,0L435.28,133.32,471,169c15,15,41,4.5,41-17V24A24,24,0,0,0,488,0Z"></path></svg></span>Report issue</a>
```

Trying your suggestion thanks :)

**Comment by stransky** [comment]
btw. It took me 2 mins with google, the answer is right here:
`
https://stackoverflow.com/questions/8454510/open-url-in-same-window-and-in-same-tab
`

**Comment by KKoukiou** [comment]
This is ready for review.

**Comment by garrett** [comment]
Err uh... that's completely invalid HTML...

```
 <a onclick='window.location.replace("extlink://github.com")'>Submit</a>
```

An anchor tag needs either a name if it's being linked to (but this is a deprecated usage) or an href. No exceptions.

**Comment by stransky** [comment]
> Err uh... that's completely invalid HTML...
> 
> ```
>  <a onclick='window.location.replace("extlink://github.com")'>Submit</a>
> ```
> 
> An anchor tag needs either a name if it's being linked to (but this is a deprecated usage) or an href. No exceptions.

This is just an example how replace window.open() with window.location.replace() to open a link in the same window. I guess you can incorporate it to WebUI accordingly.

**Comment by garrett** [comment]
Right, it's an example, but it's definite not an example of valid HTML, and not really the right way to do things.

**Review by KKoukiou — COMMENTED** [review]
@garrett this is still asking for permission to leave the page, I suggest merging this because it's fixing a big ussie with missing a way to close the opened tabs currently. And let's figure this pop ups as follow up.

**Comment by garrett** [comment]
This should not ask for confirmation to "leave the page", especially as it's not leaving the page, but if this PR improves things and we intend to fix it as a follow-up after merging this.

**Review by garrett — APPROVED** [review]
Approving on the contingency that we do a follow-up to more properly fix this and also more importantly because not merging this has more UX issues than merging it.

**Comment by AdamWill** [comment]
Did the 'follow-up' ever happen? I can't find any trace of one.

**Comment by KKoukiou** [comment]
@AdamWill fixed it in https://github.com/rhinstaller/anaconda-webui/pull/663/, because it appeared there as well, when launching gnome-control-center

**Pull request merged**
