### PR TITLE
Fix bridge crashing installation on boot.iso

### PR DESCRIPTION
**Pull request by KKoukiou**
Do not start firefox in the VM for remote installations. So far remote installations are used only for testing. Let's abuse this and switch firefox instance in the VM with a plain sleep, to avoid the crash. [1]

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2320964

### CODE REVIEW

**Comment by martinpitt** [comment]
Ugh @ lots of failures -- I'm quite sure you are not supposed to see [cockpit's login screen](https://cockpit-logs.us-east-1.linodeobjects.com/pull-485-99abb460-20241022-132556-fedora-rawhide-boot-other-bots%237016/TestStorageMountPoints-testEncryptedUnlockCockpit-fedora-rawhide-boot-127.0.0.2-2201-FAIL-1.png) anywhere during anaconda?

**Review by M4rtinK — APPROVED** [review]
Lets do this!

**Comment by KKoukiou** [comment]
For reference here is the logs with cockpit-bridge output sent to journal: https://cockpit-logs.us-east-1.linodeobjects.com/pull-485-e2ce84a1-20241024-133214-fedora-rawhide-boot-other-bots%237016/log.html#31

**Comment by martinpitt** [comment]
Debugging notes. I'll keep updating this comment to keep the email noise down:

 - @KKoukiou 's original "extra debug" commit 01fe5252917d229c1d13da8e72313e48fb294593 doesn't work -- `COCKPIT_DEBUG` is for the bridge, and `G_MESSAGES_DEBUG` is for cockpit-ws.
 - I tried to fix that in commit fc2dad5246cb0c1ade1e7a6e900bc7f78c6f22f2 but that just makes [the boot fail and time out](https://cockpit-logs.us-east-1.linodeobjects.com/pull-485-fc2dad52-20241025-040332-fedora-rawhide-boot-other-bots%237016/log). This reproduces locally.
 - `virsh console` on the boot image is completely useless. @KKoukiou didn't you have some commit that sets `console=ttyS0` somewhere? That got lost.

TBC..

**Review by martinpitt — APPROVED** [review]
Nice! ^5s!

**Review by jkonecny12 — APPROVED** [review]
Great work!
I just wonder if restarting the bridge couldn't break parallel execution of tests somehow.

**Comment by martinpitt** [comment]
@jkonecny12 They never run in parallel on the same VM. That's quite impossible to do. "parallel" tests are happening one at a time in multiple booted independent VMs.

**Comment by jkonecny12** [comment]
Sure, it makes sense when I think about it. Sorry, I didn't realize that at first.

**Comment by martinpitt** [comment]
@KKoukiou FYI, I fixed that in https://github.com/cockpit-project/cockpit/pull/21212 . Still, your new service is good for better isolation, let's keep that.

**Pull request merged**
